"""
Analysis script for gap sequences generated by MULTIPLE optimization algorithms.
Supports dynamic file counts, flexible grid plotting, and comprehensive metadata statistics.
"""

import os
import re
import math
from datetime import datetime
from collections import defaultdict, Counter
import matplotlib.pyplot as plt
import numpy as np

# --- CONFIGURATION ---

RESULTS_DIR = "../Results"

SORTING_RANGE = 10000

# Add as many files as you want here. 
# Key: Algorithm Identifier
# Value: Filename
FILES = {
    "GAv1": f"CandidateGapSequences{SORTING_RANGE}_GAv1.txt",
    "GAv2": f"CandidateGapSequences{SORTING_RANGE}_GAv2.txt",
    "GAv3": f"CandidateGapSequences{SORTING_RANGE}_GAv3.txt",
    "GAv4": f"CandidateGapSequences{SORTING_RANGE}_GAv4.txt",
    "GAv5": f"CandidateGapSequences{SORTING_RANGE}_GAv5.txt"
}

# Display names for the algorithms (used in plots and text output)
ALGO_NAMES = {
    "GAv1": "Genetic Algorithm v1",
    "GAv2": "Genetic Algorithm v2",
    "GAv3": "Genetic Algorithm v3",
    "GAv4": "Genetic Algorithm v4",
    "GAv5": "Genetic Algorithm v5"
}

# Generate output directory with current datetime
current_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
OUTPUT_DIR = f'outputs/SearchingAlgorithmsAnalysis/{current_time}'

# ---------------------

def get_dynamic_colors(num_colors):
    """Generate a dynamic colormap based on the number of files."""
    colormap = plt.colormaps['viridis']
    return [colormap(i) for i in np.linspace(0.2, 0.9, num_colors)]

def parse_file(filepath):
    """Parse a results file and extract sequence data and metadata."""
    sequences = []
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line: 
                continue
            
            population = None
            type_val = "Unknown"
            is_mutated = False
            is_validated = False
            
            # Check for NEW format: {population}|{type}|{index}...
            match_new = re.match(r'^(\d+)\|', line)
            if match_new:
                population = int(match_new.group(1))
                if ':' in line:
                    header = line.split(':', 1)[0]
                    header_parts = header.split('|')
                    type_val = header_parts[1].strip() if len(header_parts) > 1 else "Unknown"
                    is_mutated = 'Mutated' in header
                    is_validated = 'Validated' in header
            else:
                # Check for OLD format: Child183-35
                match_old = re.match(r'^[A-Za-z]+(\d+)-', line)
                if match_old:
                    population = int(match_old.group(1))
                    type_val = "Standard"
                else:
                    continue

            # Extract sequence
            if ':' in line:
                seq_part = line.split(':', 1)[1]
                sequence = [int(x) for x in seq_part.split() if x.isdigit()]
                
                if sequence:
                    sequences.append({
                        'pop': population,
                        'type': type_val,
                        'mut': is_mutated,
                        'val': is_validated,
                        'seq': sequence
                    })
                        
    return sequences

def analyze_sequences(sequences):
    """Perform analysis on parsed sequences."""
    if not sequences:
        return None
    
    populations = [s['pop'] for s in sequences]
    seqs = [s['seq'] for s in sequences]
    
    num_sequences = len(sequences)
    
    # Calculate Interval Statistics
    sorted_pops = sorted(populations)
    if len(sorted_pops) > 1:
        intervals = [sorted_pops[i+1] - sorted_pops[i] for i in range(len(sorted_pops)-1)]
        avg_interval = np.mean(intervals)
        med_interval = np.median(intervals)
        min_interval = np.min(intervals)
        max_interval = np.max(intervals)
        std_interval = np.std(intervals)
    else:
        avg_interval = med_interval = min_interval = max_interval = std_interval = 0
        
    # Analyze sequences aligned from the END
    max_len = max(len(s) for s in seqs)
    padded_seqs = []
    
    for s in seqs:
        # Pad at the front to right-align the sequences (align by their endings)
        padded = [None] * (max_len - len(s)) + s
        padded_seqs.append(padded)
        
    avg_seq, min_seq, max_seq = [], [], []
    gap_freqs_by_pos = {}
    
    for pos in range(max_len):
        values = [s[pos] for s in padded_seqs if s[pos] is not None]
        if values:
            avg_seq.append(np.mean(values))
            min_seq.append(min(values))
            max_seq.append(max(values))
            
            # Position from the end (last element = 1)
            pos_from_end = max_len - pos
            counter = Counter(values)
            gap_freqs_by_pos[pos_from_end] = {
                'counts': counter,
                'most_common': counter.most_common(10),
                'total': len(values)
            }
        else:
            avg_seq.append(0)
            min_seq.append(0)
            max_seq.append(0)
            
    # Calculate Common Endings
    beginning_counts = {}
    for n in range(1, max_len + 1):
        beginnings = []
        for s in seqs:
            if len(s) >= n:
                beginnings.append(tuple(s[-n:]))
                
        if beginnings:
            counter = Counter(beginnings)
            most_common = counter.most_common(10)
            beginning_counts[n] = {
                'counts': counter,
                'most_common': most_common,
                'total': len(beginnings)
            }
            
    # Calculate Metadata Stats (Types, Mutated, Validated)
    types_counter = Counter(s['type'] for s in sequences)
    mut_count = sum(1 for s in sequences if s['mut'])
    val_count = sum(1 for s in sequences if s['val'])
            
    return {
        'num_sequences': num_sequences,
        'avg_interval': avg_interval,
        'med_interval': med_interval,
        'min_interval': min_interval,
        'max_interval': max_interval,
        'std_interval': std_interval,
        'avg_seq': avg_seq,
        'min_seq': min_seq,
        'max_seq': max_seq,
        'gap_freqs_by_pos': gap_freqs_by_pos,
        'beginning_counts': beginning_counts,
        'types_counter': types_counter,
        'mut_count': mut_count,
        'val_count': val_count,
        'populations': sorted_pops
    }

def create_grid_subplots(num_items):
    """Creates a strictly 3-column grid based on the number of items."""
    cols = 3
    rows = math.ceil(num_items / cols)
    if rows == 0: 
        rows = 1
        
    fig, axes = plt.subplots(rows, cols, figsize=(18, 6 * rows))
    
    if rows > 1 or cols > 1:
        axes = axes.flatten() if isinstance(axes, np.ndarray) else np.array([axes]).flatten()
    else:
        axes = [axes]
        
    return fig, axes, rows, cols

def plot_num_sequences(all_results, sorted_algos, colors):
    """Plot 1: Number of sequences per algorithm."""
    fig, ax = plt.subplots(figsize=(10, 6))
    
    counts = [all_results[a]['num_sequences'] for a in sorted_algos]
    labels = [ALGO_NAMES.get(a, a) for a in sorted_algos]
    
    bars = ax.bar(labels, counts, color=colors, edgecolor='black', linewidth=1.2)
    
    for bar, count in zip(bars, counts):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                str(count), ha='center', va='bottom', fontsize=12, fontweight='bold')
                
    ax.set_ylabel('Number of Sequences', fontsize=12)
    ax.set_title(f'Number of Gap Sequences Generated by Algorithm\n(Sorting Range: {SORTING_RANGE})', fontsize=14, fontweight='bold')
    ax.set_ylim(0, max(counts) * 1.15)
    
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/plot1_num_sequences.png', dpi=150)
    plt.close()

def plot_avg_interval(all_results, sorted_algos, colors):
    """Plot 2: Average population interval between sequences (with Std Dev)."""
    fig, ax = plt.subplots(figsize=(10, 6))
    
    intervals = [all_results[a]['avg_interval'] for a in sorted_algos]
    stds = [all_results[a]['std_interval'] for a in sorted_algos]
    labels = [ALGO_NAMES.get(a, a) for a in sorted_algos]
    
    bars = ax.bar(labels, intervals, color=colors, edgecolor='black', linewidth=1.2)
    
    for bar, interval, std in zip(bars, intervals, stds):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + max(intervals)*0.02,
                f'{interval:.1f}\n± {std:.1f}', ha='center', va='bottom', fontsize=11, fontweight='bold')
                
    ax.set_ylabel('Average Population Interval', fontsize=12)
    ax.set_title(f'Average Populations Between Finding New Sequences\n(Sorting Range: {SORTING_RANGE})', fontsize=14, fontweight='bold')
    ax.set_ylim(0, max(intervals) * 1.25)
    
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/plot2_avg_interval.png', dpi=150)
    plt.close()

def plot_common_beginnings(all_results, sorted_algos, colors):
    """Plot 4: Most common sequence endings (from 1) in a flexible 3-column grid."""
    num_algos = len(sorted_algos)
    
    for n in range(1, 7):
        fig, axes, rows, cols = create_grid_subplots(num_algos)
        
        for idx, algo in enumerate(sorted_algos):
            ax = axes[idx]
            results = all_results[algo]
            algo_name = ALGO_NAMES.get(algo, algo)
            
            if n in results['beginning_counts']:
                data = results['beginning_counts'][n]
                if data['most_common']:
                    top_seqs = data['most_common'][:min(10, len(data['most_common']))]
                    
                    labels = [', '.join(map(str, seq)) for seq, _ in top_seqs][::-1]
                    percentages = [(count / data['total']) * 100 for _, count in top_seqs][::-1]
                    counts = [count for _, count in top_seqs][::-1]
                    
                    y_pos = np.arange(len(labels))
                    
                    bars = ax.barh(y_pos, percentages, color=colors[idx], 
                                   edgecolor='black', linewidth=0.8, height=0.7)
                                   
                    ax.set_yticks(y_pos)
                    ax.set_yticklabels(labels, fontsize=11)
                    ax.set_xlabel('Percentage (%)', fontsize=12)
                    ax.set_title(algo_name, fontsize=14, fontweight='bold')
                    
                    max_pct = max(percentages) if percentages else 10
                    x_limit = max(max_pct * 1.3, 5)
                    ax.set_xlim(0, x_limit)
                    ax.grid(axis='x', alpha=0.3)
                    
                    half_axis = x_limit / 2
                    for bar, pct, cnt in zip(bars, percentages, counts):
                        width = bar.get_width()
                        if width >= half_axis:
                            ax.text(width - 0.5, bar.get_y() + bar.get_height()/2,
                                   f'{pct:.1f}% ({cnt})', ha='right', va='center',
                                   fontsize=10, fontweight='bold', color='white')
                        else:
                            ax.text(width + 0.3, bar.get_y() + bar.get_height()/2,
                                   f'{pct:.1f}% ({cnt})', ha='left', va='center',
                                   fontsize=10, fontweight='bold', color='black')
            else:
                ax.text(0.5, 0.5, "No data for this length", ha='center', va='center', transform=ax.transAxes)
                ax.set_title(algo_name, fontsize=14, fontweight='bold')
                
        for idx in range(num_algos, rows * cols):
            axes[idx].set_visible(False)
            
        plt.suptitle(f'Most Common Endings - Last {n} Element{"s" if n > 1 else ""} (from 1)\n(Sorting Range: {SORTING_RANGE})', 
                     fontsize=16, fontweight='bold')
        plt.tight_layout(rect=[0, 0.03, 1, 0.95])
        plt.savefig(f'{OUTPUT_DIR}/plot4_endings_length_{n}.png', dpi=150, bbox_inches='tight')
        plt.close()

def plot_common_gaps_by_pos(all_results, sorted_algos, colors):
    """Plot 5: Most common individual gaps at each position (from 1) in a 3-column grid."""
    num_algos = len(sorted_algos)
    
    for pos in range(1, 7):
        fig, axes, rows, cols = create_grid_subplots(num_algos)
        
        for idx, algo in enumerate(sorted_algos):
            ax = axes[idx]
            results = all_results[algo]
            algo_name = ALGO_NAMES.get(algo, algo)
            
            if pos in results['gap_freqs_by_pos']:
                data = results['gap_freqs_by_pos'][pos]
                if data['most_common']:
                    top_gaps = data['most_common'][:min(10, len(data['most_common']))]
                    
                    labels = [f"{gap}" for gap, _ in top_gaps][::-1]
                    percentages = [(count / data['total']) * 100 for _, count in top_gaps][::-1]
                    counts = [count for _, count in top_gaps][::-1]
                    
                    y_pos = np.arange(len(labels))
                    
                    bars = ax.barh(y_pos, percentages, color=colors[idx], 
                                   edgecolor='black', linewidth=0.8, height=0.7)
                                   
                    ax.set_yticks(y_pos)
                    ax.set_yticklabels(labels, fontsize=11)
                    ax.set_xlabel('Percentage (%)', fontsize=12)
                    ax.set_title(algo_name, fontsize=14, fontweight='bold')
                    
                    max_pct = max(percentages) if percentages else 10
                    x_limit = max(max_pct * 1.3, 5)
                    ax.set_xlim(0, x_limit)
                    ax.grid(axis='x', alpha=0.3)
                    
                    half_axis = x_limit / 2
                    for bar, pct, cnt in zip(bars, percentages, counts):
                        width = bar.get_width()
                        if width >= half_axis:
                            ax.text(width - 0.5, bar.get_y() + bar.get_height()/2,
                                   f'{pct:.1f}% ({cnt})', ha='right', va='center',
                                   fontsize=10, fontweight='bold', color='white')
                        else:
                            ax.text(width + 0.3, bar.get_y() + bar.get_height()/2,
                                   f'{pct:.1f}% ({cnt})', ha='left', va='center',
                                   fontsize=10, fontweight='bold', color='black')
            else:
                ax.text(0.5, 0.5, "No data for this position", ha='center', va='center', transform=ax.transAxes)
                ax.set_title(algo_name, fontsize=14, fontweight='bold')
                
        for idx in range(num_algos, rows * cols):
            axes[idx].set_visible(False)
            
        plt.suptitle(f'Most Common Individual Gaps - Position {pos} (from 1)\n(Sorting Range: {SORTING_RANGE})', 
                     fontsize=16, fontweight='bold')
        plt.tight_layout(rect=[0, 0.03, 1, 0.95])
        plt.savefig(f'{OUTPUT_DIR}/plot5_common_gaps_pos_{pos}.png', dpi=150, bbox_inches='tight')
        plt.close()

def plot_common_beginnings_detailed(all_results, sorted_algos, colors):
    """Plot 6: Summary plot showing coverage trends across all algorithms in a 3-column grid."""
    num_algos = len(sorted_algos)
    fig, axes, rows, cols = create_grid_subplots(num_algos)
    
    for idx, algo in enumerate(sorted_algos):
        ax = axes[idx]
        results = all_results[algo]
        algo_name = ALGO_NAMES.get(algo, algo)
        
        n_values = list(range(1, 7))
        top1_percentages, top3_percentages, top5_percentages = [], [], []
        
        for n in n_values:
            if n in results['beginning_counts'] and results['beginning_counts'][n]['most_common']:
                data = results['beginning_counts'][n]
                top1_pct = (data['most_common'][0][1] / data['total']) * 100
                top3_pct = sum(c[1] for c in data['most_common'][:3]) / data['total'] * 100
                top5_pct = sum(c[1] for c in data['most_common'][:5]) / data['total'] * 100
                
                top1_percentages.append(top1_pct)
                top3_percentages.append(top3_pct)
                top5_percentages.append(top5_pct)
            else:
                top1_percentages.append(0)
                top3_percentages.append(0)
                top5_percentages.append(0)
                
        x = np.arange(len(n_values))
        width = 0.25
        
        bars1 = ax.bar(x - width, top1_percentages, width, label='Top 1', 
                       color=colors[idx], edgecolor='black', linewidth=1)
        bars3 = ax.bar(x, top3_percentages, width, label='Top 3', 
                       color=colors[idx], alpha=0.6, edgecolor='black', linewidth=1)
        bars5 = ax.bar(x + width, top5_percentages, width, label='Top 5', 
                       color=colors[idx], alpha=0.3, edgecolor='black', linewidth=1)
                       
        ax.set_xlabel('Length of Ending (n elements from 1)', fontsize=12)
        ax.set_ylabel('Coverage (%)', fontsize=12)
        ax.set_title(algo_name, fontsize=14, fontweight='bold')
        ax.set_xticks(x)
        ax.set_xticklabels(n_values, fontsize=11)
        ax.legend(fontsize=10, loc='upper right')
        
        max_val = max(top5_percentages) if top5_percentages else 10
        ax.set_ylim(0, max(max_val * 1.2, 10))
        ax.grid(axis='y', alpha=0.3)
        
        for bar, pct in zip(bars1, top1_percentages):
            if pct > 0:
                ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                        f'{pct:.1f}%', ha='center', va='bottom', fontsize=9, fontweight='bold')
                        
    for idx in range(num_algos, rows * cols):
        axes[idx].set_visible(False)
        
    plt.suptitle(f'Coverage of Top Sequence Endings (from 1) by Algorithm\n(Sorting Range: {SORTING_RANGE})', fontsize=16, fontweight='bold')
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.savefig(f'{OUTPUT_DIR}/plot6_endings_coverage.png', dpi=150, bbox_inches='tight')
    plt.close()

def export_to_txt(all_results, sorted_algos):
    """Export analysis results to TXT files for each algorithm."""
    for algo in sorted_algos:
        results = all_results[algo]
        algo_name = ALGO_NAMES.get(algo, algo)
        txt_path = f'{OUTPUT_DIR}/analysis_{algo}.txt'
        
        with open(txt_path, 'w', encoding='utf-8') as f:
            f.write(f"{'='*60}\n")
            f.write(f"  {algo_name} Analysis\n")
            f.write(f"{'='*60}\n\n")
            
            f.write(f"1. Number of sequences generated: {results['num_sequences']}\n\n")
            
            f.write(f"2. Population Intervals Between Sequences:\n")
            f.write(f"   Average: {results['avg_interval']:.2f}\n")
            f.write(f"   Median:  {results['med_interval']:.2f}\n")
            f.write(f"   Minimum: {results['min_interval']}\n")
            f.write(f"   Maximum: {results['max_interval']}\n")
            f.write(f"   Std Dev: {results['std_interval']:.2f}\n\n")
            
            f.write(f"3. Sequence Statistics:\n")
            f.write(f"   Min sequence: {results['min_seq']}\n")
            f.write(f"   Avg sequence: {[round(float(x), 2) for x in results['avg_seq']]}\n")
            f.write(f"   Max sequence: {results['max_seq']}\n\n")
            
            f.write(f"   Position-by-position (Aligned from End):\n")
            f.write(f"   {'Pos':<7} {'Min':<10} {'Avg':<12} {'Max':<10}\n")
            f.write(f"   {'-'*39}\n")
            max_len = len(results['avg_seq'])
            
            # Iterate backwards so the last gap (end of the list) prints first as Pos 1
            for i in range(max_len):
                idx = max_len - 1 - i
                pos_label = str(i + 1)
                f.write(f"   {pos_label:<7} {results['min_seq'][idx]:<10} {results['avg_seq'][idx]:<12.2f} {results['max_seq'][idx]:<10}\n")
                
            f.write(f"\n4. Sequence Endings (from 1):\n")
            for n, data in results['beginning_counts'].items():
                f.write(f"\n   Last {n} element(s) - {data['total']} sequences, {len(data['counts'])} unique patterns:\n")
                for seq, count in data['most_common']:
                    percentage = (count / data['total']) * 100
                    seq_str = ', '.join(map(str, seq))
                    f.write(f"      [{seq_str}]: {count} times ({percentage:.2f}%)\n")
            
            f.write(f"\n5. Most Common Gaps by Position (from 1):\n")
            for pos in range(1, min(11, max_len + 1)):  # Show up to 10 positions
                if pos in results['gap_freqs_by_pos']:
                    data = results['gap_freqs_by_pos'][pos]
                    f.write(f"\n   Position {pos} (from end) - {data['total']} valid gaps, {len(data['counts'])} unique values:\n")
                    for gap, count in data['most_common'][:5]:  # Top 5 per position
                        percentage = (count / data['total']) * 100
                        f.write(f"      Gap [{gap}]: {count} times ({percentage:.2f}%)\n")
                    
            f.write(f"\n6. Sequence Types & Flags:\n")
            f.write(f"   Total Unique Types: {len(results['types_counter'])}\n")
            f.write(f"   ---------------------------------------\n")
            for type_val, count in results['types_counter'].most_common():
                percentage = (count / results['num_sequences']) * 100
                f.write(f"   {type_val:<20} {count:>5} ({percentage:>5.1f}%)\n")
                
            f.write(f"\n   Flags Detected:\n")
            f.write(f"   ---------------------------------------\n")
            mut_pct = (results['mut_count'] / results['num_sequences']) * 100 if results['num_sequences'] else 0
            val_pct = (results['val_count'] / results['num_sequences']) * 100 if results['num_sequences'] else 0
            f.write(f"   Contains |Mutated:   {results['mut_count']:>5} ({mut_pct:>5.1f}%)\n")
            f.write(f"   Contains |Validated: {results['val_count']:>5} ({val_pct:>5.1f}%)\n")

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    all_results = {}
    
    for algo, filename in FILES.items():
        filepath = os.path.join(RESULTS_DIR, filename)
        if not os.path.exists(filepath):
            print(f"Warning: File not found: {filepath}")
            continue
            
        print(f"Processing {ALGO_NAMES.get(algo, algo)}...")
        sequences = parse_file(filepath)
        results = analyze_sequences(sequences)
        
        if results:
            all_results[algo] = results
            
    if not all_results:
        print("No valid data to analyze!")
        return
        
    sorted_algos = list(all_results.keys())
    colors = get_dynamic_colors(len(sorted_algos))
    
    print("\n" + "="*60)
    print("  EXPORTING TXT FILES")
    print("="*60)
    export_to_txt(all_results, sorted_algos)
    
    print("\n" + "="*60)
    print("  GENERATING PLOTS")
    print("="*60)
    
    plot_num_sequences(all_results, sorted_algos, colors)
    plot_avg_interval(all_results, sorted_algos, colors)
    plot_common_beginnings(all_results, sorted_algos, colors)
    plot_common_gaps_by_pos(all_results, sorted_algos, colors)
    plot_common_beginnings_detailed(all_results, sorted_algos, colors)
    
    print(f"\nAnalysis complete! Results saved to '{OUTPUT_DIR}/'")

if __name__ == "__main__":
    main()