#ifndef AUGMENTED_GENETIC_ALGORITHM_HPP
#define AUGMENTED_GENETIC_ALGORITHM_HPP


#include <iostream>
#include <vector>
#include <string>
#include <fstream>
#include "../Utilis.hpp"
#include "../Shellsort.hpp"
#include "../ShellsortComparisions.hpp"
#include "../FilesManagement.hpp"
#include "CuckooSearch.hpp"

namespace search_augmentedGA
{
    GapsSequence MutateGapsSequences(GapsSequence gapsSequence)
    {
        for (std::size_t i = 0; i + 1 < gapsSequence.gaps.size(); ++i)
        {
            if (utilis::getRandomFloat(0.0f, 1.0f) < 0.25f) //25% chance to mutate each gap
            {
                unsigned long currentGap = gapsSequence.gaps[i];

                double mutationAmount = utilis::getRandomFloat(-0.2f, 0.2f); //mutate by -20% to +20%
                double newGap = currentGap + (currentGap * mutationAmount);

                if (newGap > currentGap) { newGap = std::ceil(newGap); }
                else { newGap = std::floor(newGap); }
                if (newGap < 1) newGap = 1;

                gapsSequence.gaps[i] = static_cast<unsigned long>(newGap);
            }
        }

        gapsSequence.name += "_mutated";

        return gapsSequence;
    }

    std::vector<GapsSequence> crossParents(std::vector<GapsSequence> parents, int populationIndex)
    {
        std::vector<GapsSequence> childs;

        for (int i = 0; parents.size() >= 4 ; i += 4)
        {
            //Getting 2 random parents and removing them from the pool
            int randomIndex1 = utilis::getRandomInt(0, parents.size() - 1);
            GapsSequence parent1 = parents[randomIndex1];
            parents.erase(parents.begin() + randomIndex1);
            int randomIndex2 = utilis::getRandomInt(0, parents.size() - 1);
            GapsSequence parent2 = parents[randomIndex2];
            parents.erase(parents.begin() + randomIndex2);

            //Child 1: first half of parent1, then gaps from parent2 that are smaller than last gap in child1
            std::vector<unsigned long> child1Gaps(parent1.gaps.begin(), parent1.gaps.begin() + parent1.gaps.size() / 2);
            for (unsigned long gap : parent2.gaps)
            {
                if (gap < child1Gaps.back()) { child1Gaps.push_back(gap); }
            }

            //Child 2: first half of parent2, then gaps from parent1 that are smaller than last gap in child2
            std::vector<unsigned long> child2Gaps(parent2.gaps.begin(), parent2.gaps.begin() + parent2.gaps.size() / 2);
            for (unsigned long gap : parent1.gaps)
            {
                if (gap < child2Gaps.back()) { child2Gaps.push_back(gap); }
            }

            //Child 3: average of parent1 and parent2 gaps - as in ABC
            std::vector<unsigned long> child3Gaps;
            for (std::size_t j = 0; j < std::min(parent1.gaps.size(), parent2.gaps.size()); ++j)
            {
                child3Gaps.push_back((parent1.gaps[parent1.gaps.size() - j - 1] + parent2.gaps[parent2.gaps.size() - j - 1]) / 2);
            }
            std::reverse(child3Gaps.begin(), child3Gaps.end());

            //Child 4: average of parent1 and parent2, changed by levy flight - as in cuckoo search
            std::vector<unsigned long> child4Gaps;
            child4Gaps = search_cuckoo::performLevyFlight(GapsSequence("TempChild", child3Gaps), 1.5, 0.03).gaps;

            childs.push_back(GapsSequence("Child_Cross" + std::to_string(populationIndex) + "-" + std::to_string(i  + 1), child1Gaps));
            childs.push_back(GapsSequence("Child_Cross" + std::to_string(populationIndex) + "-" + std::to_string(i  + 2), child2Gaps));
            childs.push_back(GapsSequence("Child_Avg" + std::to_string(populationIndex) + "-" + std::to_string(i  + 3), child3Gaps));
            childs.push_back(GapsSequence("Child_Levy" + std::to_string(populationIndex) + "-" + std::to_string(i  + 4), child4Gaps));
        }

        return childs;
    }

    std::vector<GapsSequence> getNewPopulation(unsigned long sortingRange, std::vector<GapsSequence> oldPopulation, int populationIndex)
    {
        //Keep top 1 solution, rest will be generated by crossing, mutation, and new random sequences
        std::vector<GapsSequence> newPopulation = std::vector<GapsSequence>(oldPopulation.begin(), oldPopulation.begin() + 1);
        for (std::size_t i = 0; i < newPopulation.size(); ++i)
        {
            newPopulation[i].name = "Survivor" + std::to_string(populationIndex) + "-" + std::to_string(i + 1);
        }

        //Cross top ~33% to get ~66% new children solutions
        std::vector<GapsSequence> crossPopulation = std::vector<GapsSequence>(oldPopulation.begin(), oldPopulation.begin() + utilis::roundUpToEven(oldPopulation.size() / 3));
        crossPopulation = crossParents(crossPopulation, populationIndex);

        newPopulation.insert(newPopulation.end(), crossPopulation.begin(), crossPopulation.end());

        //Mutate some of the new population (survivors and childs)
        for (GapsSequence& gs : newPopulation)
        {
            if (utilis::getRandomFloat(0.0f, 1.0f) < 0.1f) //10% chance to mutate each gaps sequence
            {
                gs = MutateGapsSequences(gs);
            }
        }

        //Generate random solutions to fill the population with new genes
        for (std::size_t i = 0; newPopulation.size() < oldPopulation.size(); ++i)
        {
            newPopulation.push_back(GapsSequence(
                "Random" + std::to_string(populationIndex) + "-" + std::to_string(i+1),
                getRandomizedGaps(sortingRange)));
        }

        return newPopulation;
    }

    void endlessGapsSeeking(unsigned long sortingRange, std::vector<GapsSequence> algorithmGapsSequences, int tryoutsIterations)
    {
        std::vector<Result> results;

        std::vector<GapsSequence> alreadyFound = 
        { 
            getTokudaGaps(sortingRange),
            getCiuraGaps(sortingRange), 
            getLeeGaps(sortingRange),
            getSkeanEhrenborgJaromczykGaps(sortingRange) 
        };

        for (long i = 1; true; i++)
        {
            std::cout << "\n\nAugmented GA iteration " << i << ":\n";
            std::cout << "Gaps sequences:\n";
            for (GapsSequence sequence : algorithmGapsSequences)
            {
                sequence.PrintInstance();
                std::cout << "\n";
            }
            std::cout << "Sum of sequences: " << algorithmGapsSequences.size() << "\n";

            std::cout << "\nAugmented GA generated gaps - ";
            results = compareShellSorts(sortingRange, algorithmGapsSequences, tryoutsIterations);

            std::cout << "\nChecking for new best - ";
            GapsSequence best = compareShellSorts(sortingRange, { results[0].gapsSequence, getCiuraGaps(sortingRange), getSkeanEhrenborgJaromczykGaps(sortingRange) }, tryoutsIterations, true)[0].gapsSequence;
            if (best == results[0].gapsSequence && !isGapsSequenceIn(best, alreadyFound))
            {
                alreadyFound.push_back(best);
                std::cout << "\n\n--------------------------------------------------- NEW BEST -------------------------------------------------------\n\n";
                files::saveGapsToFile(sortingRange, "augmentedGA", best);
            }

            //creating new genetic sequences
            std::vector<GapsSequence> newGapsSequences;
            for (Result& r : results) newGapsSequences.push_back(r.gapsSequence);

            algorithmGapsSequences = getNewPopulation(sortingRange, newGapsSequences, i + 1);
        }
    }
}

#endif // !AUGMENTED_GENETIC_ALGORITHM_HPP