#ifndef GENETIC_ALGORITHM_V2_HPP
#define GENETIC_ALGORITHM_V2_HPP


#include <iostream>
#include <vector>
#include <string>
#include <fstream>
#include "../Shellsort.hpp"
#include "../ShellsortComparisions.hpp"
#include "../FilesManagement.hpp"

namespace search_genetic_v2
{
    GapsSequence MutateGapsSequence(GapsSequence gapsSequence)
    {
        for (std::size_t i = 0; i + 1 < gapsSequence.gaps.size(); ++i)
        {
            if (utilis::GetRandomFloat(0.0f, 1.0f) < 0.25f) //25% chance to mutate each gap
            {
                unsigned long currentGap = gapsSequence.gaps[i];

                double mutationAmount = utilis::GetRandomFloat(-0.2f, 0.2f); //mutate by -20% to +20%
                double newGap = currentGap + (currentGap * mutationAmount);

                if (newGap > currentGap) { newGap = std::ceil(newGap); }
                else { newGap = std::floor(newGap); }
                if (newGap < 1) newGap = 1;

                gapsSequence.gaps[i] = static_cast<unsigned long>(newGap);
            }
        }

        gapsSequence.name += "|Mutated";

        return gapsSequence;
    }

    std::vector<GapsSequence> CrossParents(std::vector<GapsSequence> parents, int populationIndex)
    {
        std::vector<GapsSequence> childs;

        for (int i = 0; parents.size() >= 2 ; i += 2)
        {
            int randomIndex1 = utilis::GetRandomInt(0, parents.size() - 1);
            GapsSequence parent1 = parents[randomIndex1];
            parents.erase(parents.begin() + randomIndex1);
            int randomIndex2 = utilis::GetRandomInt(0, parents.size() - 1);
            GapsSequence parent2 = parents[randomIndex2];
            parents.erase(parents.begin() + randomIndex2);

            std::vector<unsigned long> child1Gaps(parent1.gaps.begin(), parent1.gaps.begin() + parent1.gaps.size() / 2);
            for (unsigned long gap : parent2.gaps)
            {
                if (gap < child1Gaps.back()) { child1Gaps.push_back(gap); }
            }

            std::vector<unsigned long> child2Gaps(parent2.gaps.begin(), parent2.gaps.begin() + parent2.gaps.size() / 2);
            for (unsigned long gap : parent1.gaps)
            {
                if (gap < child2Gaps.back()) { child2Gaps.push_back(gap); }
            }

            childs.push_back(GapsSequence(std::to_string(populationIndex) + "|Child|" + std::to_string(i  + 1), child1Gaps));
            childs.push_back(GapsSequence(std::to_string(populationIndex) + "|Child|" + std::to_string(i  + 2), child2Gaps));
        }

        return childs;
    }

    std::vector<GapsSequence> GetNewPopulation(unsigned long sortingRange, std::vector<GapsSequence> oldPopulation, int populationIndex)
    {
        //Keep top 10% solutions, rest will be generated by crossing, mutation, and new random sequences
        std::vector<GapsSequence> newPopulation = std::vector<GapsSequence>(oldPopulation.begin(), oldPopulation.begin() + oldPopulation.size() / 10);
        for (std::size_t i = 0; i < newPopulation.size(); ++i)
        {
            newPopulation[i].name = std::to_string(populationIndex) + "|Survivor|" + std::to_string(i + 1);
        }

        //Cross top 50% to get 50% new children solutions
        std::vector<GapsSequence> crossPopulation = std::vector<GapsSequence>(oldPopulation.begin(), oldPopulation.begin() + oldPopulation.size() / 2);
        crossPopulation = CrossParents(crossPopulation, populationIndex);

        newPopulation.insert(newPopulation.end(), crossPopulation.begin(), crossPopulation.end());

        //Mutate some of the new population (survivors and childs)
        for (GapsSequence& gs : newPopulation)
        {
            if (utilis::GetRandomFloat(0.0f, 1.0f) < 0.1f) //10% chance to mutate each gaps sequence
            {
                gs = MutateGapsSequence(gs);
            }
        }

        //Validate population to ensure all gaps are within range to avoid fake results
        for (GapsSequence& gs : newPopulation) { gs.ValidateSequence(sortingRange); }

        //Generate random solutions to fill the population with new genes 
        for (std::size_t i = 0; newPopulation.size() < oldPopulation.size(); ++i)
        {
            newPopulation.push_back(GapsSequence(
                std::to_string(populationIndex) + "|Random|" + std::to_string(i+1),
                GetRandomizedGaps(sortingRange)));
        }

        return newPopulation;
    }

    void EndlessGapsSeeking(unsigned long sortingRange, std::vector<GapsSequence> algorithmGapsSequences, int tryoutsIterations)
    {
        std::vector<Result> results;

        std::vector<GapsSequence> alreadyFound = 
        { 
            GetTokudaGaps(sortingRange),
            GetCiuraGaps(sortingRange), 
            GetLeeGaps(sortingRange),
            GetSkeanEhrenborgJaromczykGaps(sortingRange) 
        };

        for (long i = 1; true; i++)
        {
            std::cout << "\n\nGenetic Algorithm v2 iteration " << i << ":\n";
            std::cout << "Gaps sequences:\n";
            for (GapsSequence sequence : algorithmGapsSequences)
            {
                sequence.PrintInstance();
                std::cout << "\n";
            }
            std::cout << "Sum of sequences: " << algorithmGapsSequences.size() << "\n";

            std::cout << "\nGenetic Algorithm v2 generated gaps - ";
            results = CompareShellSorts(sortingRange, algorithmGapsSequences, tryoutsIterations);

            std::cout << "\nChecking for new best - ";
            GapsSequence best = CompareShellSorts(sortingRange, { results[0].gapsSequence, GetCiuraGaps(sortingRange), GetSkeanEhrenborgJaromczykGaps(sortingRange) }, tryoutsIterations, true)[0].gapsSequence;
            if (best == results[0].gapsSequence && !IsGapsSequenceIn(best, alreadyFound))
            {
                alreadyFound.push_back(best);
                std::cout << "\n\n--------------------------------------------------- NEW BEST -------------------------------------------------------\n\n";
                files::SaveGapsToFile(sortingRange, "GAv2", best);
            }

            //creating new genetic sequences
            std::vector<GapsSequence> newGapsSequences;
            for (Result& r : results) newGapsSequences.push_back(r.gapsSequence);

            algorithmGapsSequences = GetNewPopulation(sortingRange, newGapsSequences, i + 1);
        }
    }
}

#endif // !GENETIC_ALGORITHM_V2_HPP