#ifndef GENETIC_ALGORITHM_V1_HPP
#define GENETIC_ALGORITHM_V1_HPP


#include <iostream>
#include <vector>
#include <string>
#include <fstream>
#include "../Shellsort.hpp"
#include "../ShellsortComparisions.hpp"
#include "../FilesManagement.hpp"

namespace search_genetic_v1
{
    
    std::vector<GapsSequence> CrossParents(std::vector<GapsSequence> parents, int populationIndex)
    {
        std::vector<GapsSequence> childs;

        for (std::size_t i = 0; i < parents.size(); i += 2)
        {
            GapsSequence parent1 = parents[i];
            GapsSequence parent2;
            if (i + 1 < parents.size()) { parent2 = parents[i + 1]; }
            else { parent2 = parents[0]; }

            std::vector<unsigned long> child1Gaps(parent1.gaps.begin(), parent1.gaps.begin() + parent1.gaps.size() / 2);
            for (unsigned long gap : parent2.gaps)
            {
                if (gap < child1Gaps.back()) { child1Gaps.push_back(gap); }
            }

            std::vector<unsigned long> child2Gaps(parent2.gaps.begin(), parent2.gaps.begin() + parent2.gaps.size() / 2);
            for (unsigned long gap : parent1.gaps)
            {
                if (gap < child2Gaps.back()) { child2Gaps.push_back(gap); }
            }

            childs.push_back(GapsSequence("Child" + std::to_string(populationIndex) + "-" + std::to_string(i + 1), child1Gaps));
            childs.push_back(GapsSequence("Child" + std::to_string(populationIndex) + "-" + std::to_string(i + 2), child2Gaps));
        }

        return childs;
    }

    std::vector<GapsSequence> GetNewPopulation(unsigned long sortingRange, std::vector<GapsSequence> oldPopulation, int populationIndex)
    {
        //Take top 50% of old population to be parents for the next generation
        std::vector<GapsSequence> newPopulation = std::vector<GapsSequence>(oldPopulation.begin(), oldPopulation.begin() + oldPopulation.size() / 2);

        //Exchange previous population with new childs generated by crossing parents (50%)
        newPopulation = CrossParents(newPopulation, populationIndex);

        //Fill the rest of the population with new random solutions to maintain diversity in genes (50%)
        for (std::size_t i = newPopulation.size(); i < oldPopulation.size(); i++)
        {
            newPopulation.push_back(GapsSequence(
                "Random" + std::to_string(populationIndex) + "-" + std::to_string(i+1),
                GetRandomizedGaps(sortingRange)));
        }

        return newPopulation;
    }

    void EndlessGapsSeeking(unsigned long sortingRange, std::vector<GapsSequence> algorithmGapsSequences, int tryoutsIterations)
    {
        std::vector<Result> results;

        std::vector<GapsSequence> alreadyFound = 
        { 
            GetTokudaGaps(sortingRange),
            GetCiuraGaps(sortingRange), 
            GetLeeGaps(sortingRange),
            GetSkeanEhrenborgJaromczykGaps(sortingRange) 
        };

        for (long i = 1; true; i++)
        {
            std::cout << "\n\nGenetic Algorithm v2 iteration " << i << ":\n";
            std::cout << "Gaps sequences:\n";
            for (GapsSequence sequence : algorithmGapsSequences)
            {
                sequence.PrintInstance();
                std::cout << "\n";
            }
            std::cout << "Sum of sequences: " << algorithmGapsSequences.size() << "\n";

            std::cout << "\nGenetic Algorithm v2 generated gaps";
            results = CompareShellSorts(sortingRange, algorithmGapsSequences, tryoutsIterations);

            std::cout << "\nChecking for new best";
            GapsSequence best = CompareShellSorts(sortingRange, { results[0].gapsSequence, GetCiuraGaps(sortingRange), GetSkeanEhrenborgJaromczykGaps(sortingRange) }, tryoutsIterations, true)[0].gapsSequence;
            if (best == results[0].gapsSequence && !IsGapsSequenceIn(best, alreadyFound))
            {
                alreadyFound.push_back(best);
                std::cout << "\n\nNEW CANDIDATE SEQUENCE ---------------------------- NEW CANDIDATE SEQUENCE ---------------------------- NEW CANDIDATE SEQUENCE\n\n";
                files::SaveGapsToFile(sortingRange, "GAv2", best);
            }

            //creating new genetic sequences
            std::vector<GapsSequence> newGapsSequences;
            for (Result& r : results) newGapsSequences.push_back(r.gapsSequence);

            algorithmGapsSequences = GetNewPopulation(sortingRange, newGapsSequences, i + 1);
        }
    }
}

#endif // !GENETIC_ALGORITHM_V1_HPP